<Project>
  <PropertyGroup>
    <PackageId>$(AssemblyName)</PackageId>
    <Version>9.0.1.1</Version>
    <Authors>Ruslan Balanukhin</Authors>
    <Company>Rationale One</Company>
    <Product>FFmpeg.AutoGen</Product>
    <Copyright>Copyright © Ruslan Balanukhin 2025 All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/Ruslan-B/FFmpeg.AutoGen</PackageProjectUrl>
    <RepositoryType>Git</RepositoryType>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageTags>ffmpeg</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE.txt" Link="LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)README.md" Link="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  
</Project>
