/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.0.1-4-ga5ebb3d25e-20220605"
#endif /* AVUTIL_FFVERSION_H */
