/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.3.1-2020-10-01-full_build-www.gyan.dev"
#endif /* AVUTIL_FFVERSION_H */
